image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

pages:
  stage: deploy
  only:
    - master
  before_script:
    - 'yarn config set cache-folder .yarn'
    - 'yarn install'
  script:
    - 'yarn build'
    - 'rm -rf public'
    - 'cp -pr dist public'
  artifacts:
    paths:
      - public
