image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

pages:
  stage: deploy
  only:
    - master
  before_script:
    - 'npm install'
  script:
    - 'npm build'
    - 'cp -pr dist public'
  artifacts:
    paths:
      - public
